# docker compose file for base notebook
version: '3.1'

services:
  spark-base:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        http_proxy:
        https_proxy:
        ftp_proxy:
    image: spark-base:spark3.5.0-hadoop3-java8
    container_name: spark-base
