# docker compose file for base notebook
version: '3.1'

services:
  hadoop-base:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        http_proxy:
        https_proxy:
        ftp_proxy:
    image: hadoop-base:hadoop3.3.6-java8
    container_name: hadoop-base
